version: "3.9"

services:
  backend:
    build: .
    container_name: crud-backend
    ports:
      - "3000:3000"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: cruddb
      PG_HOST: db
      PG_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: crud-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: